name: Legitify Test - Show All Issues
on:
  workflow_dispatch:

  schedule:
    - cron: '0 11 * * 1-5'
  push:
    branches: [ "master" ]  

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        
      - name: Run Legitify Without Ignoring Policies
        uses: Legit-Labs/legitify@038aa49473a6974a3ef79f6c76b949b689d23282 # main
        with:
          github_token: ${{ secrets.PAT_FOR_LEGITIFY }}
          upload_code_scanning: true
          # No ignore-policies - see everything
